/** Interface for country data - simplified for use with Google libphonenumber */
export interface Country {
    /** Country name in English */
    name: string;
    /** ISO 3166-1 alpha-2 country code */
    code: string;
    /** International dialing code */
    dialCode: string;
    /** Unicode flag emoji */
    flag: string;
    /** Path to flag image */
    flagImage?: string;
    /** Country name in native language */
    nativeName: string;
    /** Realistic mobile number placeholder example (without country code) */
    placeholder?: string;
}
/** Comprehensive list of all countries with their telephone data */
export const COUNTRIES_DATA: Country[] = [
    {
        name: 'United States',
        code: 'US',
        dialCode: '+1',
        flag: '🇺🇸',
        flagImage: 'assets/images/flags/us.png',
        nativeName: 'United States',
        placeholder: '2015550123',
    },
    {
        name: 'United Kingdom',
        code: 'GB',
        dialCode: '+44',
        flag: '🇬🇧',
        flagImage: 'assets/images/flags/gb.png',
        nativeName: 'United Kingdom',
        placeholder: '07400123456',
    },
    // A
    {
        name: 'Åland Islands',
        code: 'AX',
        dialCode: '+358',
        flag: '🇦🇽',
        flagImage: 'assets/images/flags/ax.png',
        nativeName: 'Åland',
        placeholder: '0401234567',
    },
    {
        name: 'Afghanistan',
        code: 'AF',
        dialCode: '+93',
        flag: '🇦🇫',
        flagImage: 'assets/images/flags/af.png',
        nativeName: 'افغانستان',
        placeholder: '0701234567',
    },
    {
        name: 'Albania',
        code: 'AL',
        dialCode: '+355',
        flag: '🇦🇱',
        flagImage: 'assets/images/flags/al.png',
        nativeName: 'Shqipëria',
        placeholder: '0671234567',
    },
    {
        name: 'Algeria',
        code: 'DZ',
        dialCode: '+213',
        flag: '🇩🇿',
        flagImage: 'assets/images/flags/dz.png',
        nativeName: 'الجزائر',
        placeholder: '0551234567',
    },
    {
        name: 'American Samoa',
        code: 'AS',
        dialCode: '+1684',
        flag: '🇦🇸',
        flagImage: 'assets/images/flags/as.png',
        nativeName: 'Amerika Sāmoa',
        placeholder: '6841234567',
    },
    {
        name: 'Andorra',
        code: 'AD',
        dialCode: '+376',
        flag: '🇦🇩',
        flagImage: 'assets/images/flags/ad.png',
        nativeName: 'Andorra',
        placeholder: '312345',
    },
    {
        name: 'Angola',
        code: 'AO',
        dialCode: '+244',
        flag: '🇦🇴',
        flagImage: 'assets/images/flags/ao.png',
        nativeName: 'Angola',
        placeholder: '923123456',
    },
    {
        name: 'Anguilla',
        code: 'AI',
        dialCode: '+1264',
        flag: '🇦🇮',
        flagImage: 'assets/images/flags/ai.png',
        nativeName: 'Anguilla',
        placeholder: '2642351234',
    },
    {
        name: 'Antigua and Barbuda',
        code: 'AG',
        dialCode: '+1268',
        flag: '🇦🇬',
        flagImage: 'assets/images/flags/ag.png',
        nativeName: 'Antigua and Barbuda',
        placeholder: '2687201234',
    },
    {
        name: 'Argentina',
        code: 'AR',
        dialCode: '+54',
        flag: '🇦🇷',
        flagImage: 'assets/images/flags/ar.png',
        nativeName: 'Argentina',
        placeholder: '1123456789',
    },
    {
        name: 'Armenia',
        code: 'AM',
        dialCode: '+374',
        flag: '🇦🇲',
        flagImage: 'assets/images/flags/am.png',
        nativeName: 'Հայաստան',
        placeholder: '077123456',
    },
    {
        name: 'Aruba',
        code: 'AW',
        dialCode: '+297',
        flag: '🇦🇼',
        flagImage: 'assets/images/flags/aw.png',
        nativeName: 'Aruba',
        placeholder: '5601234',
    },
    {
        name: 'Australia',
        code: 'AU',
        dialCode: '+61',
        flag: '🇦🇺',
        flagImage: 'assets/images/flags/au.png',
        nativeName: 'Australia',
        placeholder: '0412345678',
    },
    {
        name: 'Austria',
        code: 'AT',
        dialCode: '+43',
        flag: '🇦🇹',
        flagImage: 'assets/images/flags/at.png',
        nativeName: 'Österreich',
        placeholder: '06641234567',
    },
    {
        name: 'Azerbaijan',
        code: 'AZ',
        dialCode: '+994',
        flag: '🇦🇿',
        flagImage: 'assets/images/flags/az.png',
        nativeName: 'Azərbaycan',
        placeholder: '0401234567',
    },
    // B
    {
        name: 'Bahamas',
        code: 'BS',
        dialCode: '+1242',
        flag: '🇧🇸',
        flagImage: 'assets/images/flags/bs.png',
        nativeName: 'The Bahamas',
        placeholder: '2423591234',
    },
    {
        name: 'Bahrain',
        code: 'BH',
        dialCode: '+973',
        flag: '🇧🇭',
        flagImage: 'assets/images/flags/bh.png',
        nativeName: 'البحرين',
        placeholder: '36001234',
    },
    {
        name: 'Bangladesh',
        code: 'BD',
        dialCode: '+880',
        flag: '🇧🇩',
        flagImage: 'assets/images/flags/bd.png',
        nativeName: 'বাংলাদেশ',
        placeholder: '01712345678',
    },
    {
        name: 'Barbados',
        code: 'BB',
        dialCode: '+1246',
        flag: '🇧🇧',
        flagImage: 'assets/images/flags/bb.png',
        nativeName: 'Barbados',
        placeholder: '2462501234',
    },
    {
        name: 'Belarus',
        code: 'BY',
        dialCode: '+375',
        flag: '🇧🇾',
        flagImage: 'assets/images/flags/by.png',
        nativeName: 'Беларусь',
        placeholder: '0291234567',
    },
    {
        name: 'Belgium',
        code: 'BE',
        dialCode: '+32',
        flag: '🇧🇪',
        flagImage: 'assets/images/flags/be.png',
        nativeName: 'België / Belgique',
        placeholder: '0470123456',
    },
    {
        name: 'Belize',
        code: 'BZ',
        dialCode: '+501',
        flag: '🇧🇿',
        flagImage: 'assets/images/flags/bz.png',
        nativeName: 'Belize',
        placeholder: '6221234',
    },
    {
        name: 'Benin',
        code: 'BJ',
        dialCode: '+229',
        flag: '🇧🇯',
        flagImage: 'assets/images/flags/bj.png',
        nativeName: 'Bénin',
        placeholder: '97123456',
    },
    {
        name: 'Bermuda',
        code: 'BM',
        dialCode: '+1441',
        flag: '🇧🇲',
        flagImage: 'assets/images/flags/bm.png',
        nativeName: 'Bermuda',
        placeholder: '4412921234',
    },
    {
        name: 'Bhutan',
        code: 'BT',
        dialCode: '+975',
        flag: '🇧🇹',
        flagImage: 'assets/images/flags/bt.png',
        nativeName: 'འབྲུག',
        placeholder: '17123456',
    },
    {
        name: 'Bolivia',
        code: 'BO',
        dialCode: '+591',
        flag: '🇧🇴',
        flagImage: 'assets/images/flags/bo.png',
        nativeName: 'Bolivia',
        placeholder: '71234567',
    },
    {
        name: 'Bosnia and Herzegovina',
        code: 'BA',
        dialCode: '+387',
        flag: '🇧🇦',
        flagImage: 'assets/images/flags/ba.png',
        nativeName: 'Bosna i Hercegovina',
        placeholder: '061123456',
    },
    {
        name: 'Botswana',
        code: 'BW',
        dialCode: '+267',
        flag: '🇧🇼',
        flagImage: 'assets/images/flags/bw.png',
        nativeName: 'Botswana',
        placeholder: '71123456',
    },
    {
        name: 'Brazil',
        code: 'BR',
        dialCode: '+55',
        flag: '🇧🇷',
        flagImage: 'assets/images/flags/br.png',
        nativeName: 'Brasil',
        placeholder: '11987654321',
    },
    {
        name: 'British Indian Ocean Territory',
        code: 'IO',
        dialCode: '+246',
        flag: '🇮🇴',
        flagImage: 'assets/images/flags/io.png',
        nativeName: 'British Indian Ocean Territory',
        placeholder: '3801401',
    },
    {
        name: 'British Virgin Islands',
        code: 'VG',
        dialCode: '+1284',
        flag: '🇻🇬',
        flagImage: 'assets/images/flags/vg.png',
        nativeName: 'British Virgin Islands',
        placeholder: '2843001234',
    },
    {
        name: 'Brunei',
        code: 'BN',
        dialCode: '+673',
        flag: '🇧🇳',
        flagImage: 'assets/images/flags/bn.png',
        nativeName: 'Brunei Darussalam',
        placeholder: '7121234',
    },
    {
        name: 'Bulgaria',
        code: 'BG',
        dialCode: '+359',
        flag: '🇧🇬',
        flagImage: 'assets/images/flags/bg.png',
        nativeName: 'България',
        placeholder: '0871234567',
    },
    {
        name: 'Burkina Faso',
        code: 'BF',
        dialCode: '+226',
        flag: '🇧🇫',
        flagImage: 'assets/images/flags/bf.png',
        nativeName: 'Burkina Faso',
        placeholder: '70123456',
    },
    {
        name: 'Burundi',
        code: 'BI',
        dialCode: '+257',
        flag: '🇧🇮',
        flagImage: 'assets/images/flags/bi.png',
        nativeName: 'Burundi',
        placeholder: '79561234',
    },
    // C
    {
        name: 'Cambodia',
        code: 'KH',
        dialCode: '+855',
        flag: '🇰🇭',
        flagImage: 'assets/images/flags/kh.png',
        nativeName: 'កម្ពុជា',
        placeholder: '012345678',
    },
    {
        name: 'Cameroon',
        code: 'CM',
        dialCode: '+237',
        flag: '🇨🇲',
        flagImage: 'assets/images/flags/cm.png',
        nativeName: 'Cameroun',
        placeholder: '671234567',
    },
    {
        name: 'Canada',
        code: 'CA',
        dialCode: '+1',
        flag: '🇨🇦',
        flagImage: 'assets/images/flags/ca.png',
        nativeName: 'Canada',
        placeholder: '4165551234',
    },
    {
        name: 'Cape Verde',
        code: 'CV',
        dialCode: '+238',
        flag: '🇨🇻',
        flagImage: 'assets/images/flags/cv.png',
        nativeName: 'Cabo Verde',
        placeholder: '9911234',
    },
    {
        name: 'Caribbean Netherlands',
        code: 'BQ',
        dialCode: '+599',
        flag: '🇧🇶',
        flagImage: 'assets/images/flags/bq.png',
        nativeName: 'Caribbean Netherlands',
    },
    {
        name: 'Cayman Islands',
        code: 'KY',
        dialCode: '+1345',
        flag: '🇰🇾',
        flagImage: 'assets/images/flags/ky.png',
        nativeName: 'Cayman Islands',
        placeholder: '3453231234',
    },
    {
        name: 'Central African Republic',
        code: 'CF',
        dialCode: '+236',
        flag: '🇨🇫',
        flagImage: 'assets/images/flags/cf.png',
        nativeName: 'République Centrafricaine',
        placeholder: '72001234',
    },
    {
        name: 'Chad',
        code: 'TD',
        dialCode: '+235',
        flag: '🇹🇩',
        flagImage: 'assets/images/flags/td.png',
        nativeName: 'تشاد',
        placeholder: '63012345',
    },
    {
        name: 'Chile',
        code: 'CL',
        dialCode: '+56',
        flag: '🇨🇱',
        flagImage: 'assets/images/flags/cl.png',
        nativeName: 'Chile',
        placeholder: '912345678',
    },
    {
        name: 'China',
        code: 'CN',
        dialCode: '+86',
        flag: '🇨🇳',
        flagImage: 'assets/images/flags/cn.png',
        nativeName: '中国',
        placeholder: '13800138000',
    },
    {
        name: 'Christmas Island',
        code: 'CX',
        dialCode: '+61',
        flag: '🇨🇽',
        flagImage: 'assets/images/flags/cx.png',
        nativeName: 'Christmas Island',
        placeholder: '0412345678',
    },
    {
        name: 'Cocos (Keeling) Islands',
        code: 'CC',
        dialCode: '+61',
        flag: '🇨🇨',
        flagImage: 'assets/images/flags/cc.png',
        nativeName: 'Cocos (Keeling) Islands',
        placeholder: '0412345678',
    },
    {
        name: 'Colombia',
        code: 'CO',
        dialCode: '+57',
        flag: '🇨🇴',
        flagImage: 'assets/images/flags/co.png',
        nativeName: 'Colombia',
        placeholder: '3001234567',
    },
    {
        name: 'Comoros',
        code: 'KM',
        dialCode: '+269',
        flag: '🇰🇲',
        flagImage: 'assets/images/flags/km.png',
        nativeName: 'Komori',
        placeholder: '3211234',
    },
    {
        name: 'Congo',
        code: 'CG',
        dialCode: '+242',
        flag: '🇨🇬',
        flagImage: 'assets/images/flags/cg.png',
        nativeName: 'Congo',
        placeholder: '061234567',
    },
    {
        name: 'Democratic Republic of the Congo',
        code: 'CD',
        dialCode: '+243',
        flag: '🇨🇩',
        flagImage: 'assets/images/flags/cd.png',
        nativeName: 'République Démocratique du Congo',
        placeholder: '0991234567',
    },
    {
        name: 'Cook Islands',
        code: 'CK',
        dialCode: '+682',
        flag: '🇨🇰',
        flagImage: 'assets/images/flags/ck.png',
        nativeName: 'Cook Islands',
        placeholder: '71234',
    },
    {
        name: 'Costa Rica',
        code: 'CR',
        dialCode: '+506',
        flag: '🇨🇷',
        flagImage: 'assets/images/flags/cr.png',
        nativeName: 'Costa Rica',
        placeholder: '83123456',
    },
    {
        name: 'Croatia',
        code: 'HR',
        dialCode: '+385',
        flag: '🇭🇷',
        flagImage: 'assets/images/flags/hr.png',
        nativeName: 'Hrvatska',
        placeholder: '0912345678',
    },
    {
        name: 'Cuba',
        code: 'CU',
        dialCode: '+53',
        flag: '🇨🇺',
        flagImage: 'assets/images/flags/cu.png',
        nativeName: 'Cuba',
        placeholder: '051234567',
    },
    {
        name: 'Curaçao',
        code: 'CW',
        dialCode: '+599',
        flag: '🇨🇼',
        flagImage: 'assets/images/flags/cw.png',
        nativeName: 'Curaçao',
        placeholder: '95512345',
    },
    {
        name: 'Cyprus',
        code: 'CY',
        dialCode: '+357',
        flag: '🇨🇾',
        flagImage: 'assets/images/flags/cy.png',
        nativeName: 'Κύπρος',
        placeholder: '96123456',
    },
    {
        name: 'Czech Republic',
        code: 'CZ',
        dialCode: '+420',
        flag: '🇨🇿',
        flagImage: 'assets/images/flags/cz.png',
        nativeName: 'Česká republika',
        placeholder: '601234567',
    },
    // D
    {
        name: 'Denmark',
        code: 'DK',
        dialCode: '+45',
        flag: '🇩🇰',
        flagImage: 'assets/images/flags/dk.png',
        nativeName: 'Danmark',
        placeholder: '20123456',
    },
    {
        name: 'Djibouti',
        code: 'DJ',
        dialCode: '+253',
        flag: '🇩🇯',
        flagImage: 'assets/images/flags/dj.png',
        nativeName: 'Djibouti',
        placeholder: '77831001',
    },
    {
        name: 'Dominica',
        code: 'DM',
        dialCode: '+1767',
        flag: '🇩🇲',
        flagImage: 'assets/images/flags/dm.png',
        nativeName: 'Dominica',
        placeholder: '7672251234',
    },
    {
        name: 'Dominican Republic',
        code: 'DO',
        dialCode: '+1809',
        flag: '🇩🇴',
        flagImage: 'assets/images/flags/do.png',
        nativeName: 'República Dominicana',
        placeholder: '8091234567',
    },
    // E
    {
        name: 'Ecuador',
        code: 'EC',
        dialCode: '+593',
        flag: '🇪🇨',
        flagImage: 'assets/images/flags/ec.png',
        nativeName: 'Ecuador',
        placeholder: '0991234567',
    },
    {
        name: 'Egypt',
        code: 'EG',
        dialCode: '+20',
        flag: '🇪🇬',
        flagImage: 'assets/images/flags/eg.png',
        nativeName: 'مصر',
        placeholder: '01001234567',
    },
    {
        name: 'El Salvador',
        code: 'SV',
        dialCode: '+503',
        flag: '🇸🇻',
        flagImage: 'assets/images/flags/sv.png',
        nativeName: 'El Salvador',
        placeholder: '70123456',
    },
    {
        name: 'Equatorial Guinea',
        code: 'GQ',
        dialCode: '+240',
        flag: '🇬🇶',
        flagImage: 'assets/images/flags/gq.png',
        nativeName: 'Guinea Ecuatorial',
        placeholder: '222123456',
    },
    {
        name: 'Eritrea',
        code: 'ER',
        dialCode: '+291',
        flag: '🇪🇷',
        flagImage: 'assets/images/flags/er.png',
        nativeName: 'ኤርትራ',
        placeholder: '07123456',
    },
    {
        name: 'Estonia',
        code: 'EE',
        dialCode: '+372',
        flag: '🇪🇪',
        flagImage: 'assets/images/flags/ee.png',
        nativeName: 'Eesti',
        placeholder: '51234567',
    },
    {
        name: 'Eswatini',
        code: 'SZ',
        dialCode: '+268',
        flag: '🇸🇿',
        flagImage: 'assets/images/flags/sz.png',
        nativeName: 'Eswatini',
        placeholder: '76123456',
    },
    {
        name: 'Ethiopia',
        code: 'ET',
        dialCode: '+251',
        flag: '🇪🇹',
        flagImage: 'assets/images/flags/et.png',
        nativeName: 'ኢትዮጵያ',
        placeholder: '0911234567',
    },
    // F
    {
        name: 'Falkland Islands',
        code: 'FK',
        dialCode: '+500',
        flag: '🇫🇰',
        flagImage: 'assets/images/flags/fk.png',
        nativeName: 'Falkland Islands',
        placeholder: '51234',
    },
    {
        name: 'Faroe Islands',
        code: 'FO',
        dialCode: '+298',
        flag: '🇫🇴',
        flagImage: 'assets/images/flags/fo.png',
        nativeName: 'Føroyar',
        placeholder: '211234',
    },
    {
        name: 'Fiji',
        code: 'FJ',
        dialCode: '+679',
        flag: '🇫🇯',
        flagImage: 'assets/images/flags/fj.png',
        nativeName: 'Fiji',
        placeholder: '7012345',
    },
    {
        name: 'Finland',
        code: 'FI',
        dialCode: '+358',
        flag: '🇫🇮',
        flagImage: 'assets/images/flags/fi.png',
        nativeName: 'Suomi',
        placeholder: '0401234567',
    },
    {
        name: 'France',
        code: 'FR',
        dialCode: '+33',
        flag: '🇫🇷',
        flagImage: 'assets/images/flags/fr.png',
        nativeName: 'France',
        placeholder: '0612345678',
    },
    {
        name: 'French Guiana',
        code: 'GF',
        dialCode: '+594',
        flag: '🇬🇫',
        flagImage: 'assets/images/flags/gf.png',
        nativeName: 'Guyane française',
        placeholder: '0694201234',
    },
    {
        name: 'French Polynesia',
        code: 'PF',
        dialCode: '+689',
        flag: '🇵🇫',
        flagImage: 'assets/images/flags/pf.png',
        nativeName: 'Polynésie française',
        placeholder: '87123456',
    },
    // G
    {
        name: 'Gabon',
        code: 'GA',
        dialCode: '+241',
        flag: '🇬🇦',
        flagImage: 'assets/images/flags/ga.png',
        nativeName: 'Gabon',
        placeholder: '06031234',
    },
    {
        name: 'Gambia',
        code: 'GM',
        dialCode: '+220',
        flag: '🇬🇲',
        flagImage: 'assets/images/flags/gm.png',
        nativeName: 'Gambia',
        placeholder: '3012345',
    },
    {
        name: 'Georgia',
        code: 'GE',
        dialCode: '+995',
        flag: '🇬🇪',
        flagImage: 'assets/images/flags/ge.png',
        nativeName: 'საქართველო',
        placeholder: '555123456',
    },
    {
        name: 'Germany',
        code: 'DE',
        dialCode: '+49',
        flag: '🇩🇪',
        flagImage: 'assets/images/flags/de.png',
        nativeName: 'Deutschland',
        placeholder: '01512345678',
    },
    {
        name: 'Ghana',
        code: 'GH',
        dialCode: '+233',
        flag: '🇬🇭',
        flagImage: 'assets/images/flags/gh.png',
        nativeName: 'Ghana',
        placeholder: '0241234567',
    },
    {
        name: 'Gibraltar',
        code: 'GI',
        dialCode: '+350',
        flag: '🇬🇮',
        flagImage: 'assets/images/flags/gi.png',
        nativeName: 'Gibraltar',
        placeholder: '57123456',
    },
    {
        name: 'Greece',
        code: 'GR',
        dialCode: '+30',
        flag: '🇬🇷',
        flagImage: 'assets/images/flags/gr.png',
        nativeName: 'Ελλάδα',
        placeholder: '6912345678',
    },
    {
        name: 'Greenland',
        code: 'GL',
        dialCode: '+299',
        flag: '🇬🇱',
        flagImage: 'assets/images/flags/gl.png',
        nativeName: 'Kalaallit Nunaat',
        placeholder: '321234',
    },
    {
        name: 'Grenada',
        code: 'GD',
        dialCode: '+1473',
        flag: '🇬🇩',
        flagImage: 'assets/images/flags/gd.png',
        nativeName: 'Grenada',
        placeholder: '4734031234',
    },
    {
        name: 'Guadeloupe',
        code: 'GP',
        dialCode: '+590',
        flag: '🇬🇵',
        flagImage: 'assets/images/flags/gp.png',
        nativeName: 'Guadeloupe',
        placeholder: '0690001234',
    },
    {
        name: 'Guam',
        code: 'GU',
        dialCode: '+1671',
        flag: '🇬🇺',
        flagImage: 'assets/images/flags/gu.png',
        nativeName: 'Guåhan',
        placeholder: '6713001234',
    },
    {
        name: 'Guatemala',
        code: 'GT',
        dialCode: '+502',
        flag: '🇬🇹',
        flagImage: 'assets/images/flags/gt.png',
        nativeName: 'Guatemala',
        placeholder: '51234567',
    },
    {
        name: 'Guernsey',
        code: 'GG',
        dialCode: '+44',
        flag: '🇬🇬',
        flagImage: 'assets/images/flags/gg.png',
        nativeName: 'Guernsey',
        placeholder: '07781123456',
    },
    {
        name: 'Guinea',
        code: 'GN',
        dialCode: '+224',
        flag: '🇬🇳',
        flagImage: 'assets/images/flags/gn.png',
        nativeName: 'Guinée',
        placeholder: '601123456',
    },
    {
        name: 'Guinea-Bissau',
        code: 'GW',
        dialCode: '+245',
        flag: '🇬🇼',
        flagImage: 'assets/images/flags/gw.png',
        nativeName: 'Guiné-Bissau',
        placeholder: '955012345',
    },
    {
        name: 'Guyana',
        code: 'GY',
        dialCode: '+592',
        flag: '🇬🇾',
        flagImage: 'assets/images/flags/gy.png',
        nativeName: 'Guyana',
        placeholder: '6091234567',
    },
    // H
    {
        name: 'Haiti',
        code: 'HT',
        dialCode: '+509',
        flag: '🇭🇹',
        flagImage: 'assets/images/flags/ht.png',
        nativeName: 'Haïti',
        placeholder: '34101234',
    },
    {
        name: 'Honduras',
        code: 'HN',
        dialCode: '+504',
        flag: '🇭🇳',
        flagImage: 'assets/images/flags/hn.png',
        nativeName: 'Honduras',
        placeholder: '91234567',
    },
    {
        name: 'Hong Kong',
        code: 'HK',
        dialCode: '+852',
        flag: '🇭🇰',
        flagImage: 'assets/images/flags/hk.png',
        nativeName: '香港',
        placeholder: '51234567',
    },
    {
        name: 'Hungary',
        code: 'HU',
        dialCode: '+36',
        flag: '🇭🇺',
        flagImage: 'assets/images/flags/hu.png',
        nativeName: 'Magyarország',
        placeholder: '301234567',
    },
    // I
    {
        name: 'Iceland',
        code: 'IS',
        dialCode: '+354',
        flag: '🇮🇸',
        flagImage: 'assets/images/flags/is.png',
        nativeName: 'Ísland',
        placeholder: '6111234',
    },
    {
        name: 'India',
        code: 'IN',
        dialCode: '+91',
        flag: '🇮🇳',
        flagImage: 'assets/images/flags/in.png',
        nativeName: 'भारत',
        placeholder: '9876543210',
    },
    {
        name: 'Indonesia',
        code: 'ID',
        dialCode: '+62',
        flag: '🇮🇩',
        flagImage: 'assets/images/flags/id.png',
        nativeName: 'Indonesia',
        placeholder: '081234567890',
    },
    {
        name: 'Iran',
        code: 'IR',
        dialCode: '+98',
        flag: '🇮🇷',
        flagImage: 'assets/images/flags/ir.png',
        nativeName: 'ایران',
        placeholder: '09121234567',
    },
    {
        name: 'Iraq',
        code: 'IQ',
        dialCode: '+964',
        flag: '🇮🇶',
        flagImage: 'assets/images/flags/iq.png',
        nativeName: 'العراق',
        placeholder: '07901234567',
    },
    {
        name: 'Ireland',
        code: 'IE',
        dialCode: '+353',
        flag: '🇮🇪',
        flagImage: 'assets/images/flags/ie.png',
        nativeName: 'Éire',
        placeholder: '0871234567',
    },
    {
        name: 'Isle of Man',
        code: 'IM',
        dialCode: '+44',
        flag: '🇮🇲',
        flagImage: 'assets/images/flags/im.png',
        nativeName: 'Isle of Man',
        placeholder: '07924123456',
    },
    {
        name: 'Israel',
        code: 'IL',
        dialCode: '+972',
        flag: '🇮🇱',
        flagImage: 'assets/images/flags/il.png',
        nativeName: 'ישראל',
        placeholder: '0501234567',
    },
    {
        name: 'Italy',
        code: 'IT',
        dialCode: '+39',
        flag: '🇮🇹',
        flagImage: 'assets/images/flags/it.png',
        nativeName: 'Italia',
        placeholder: '3123456789',
    },
    {
        name: 'Ivory Coast',
        code: 'CI',
        dialCode: '+225',
        flag: '🇨🇮',
        flagImage: 'assets/images/flags/ci.png',
        nativeName: "Côte d'Ivoire",
    },
    // J
    {
        name: 'Jamaica',
        code: 'JM',
        dialCode: '+1876',
        flag: '🇯🇲',
        flagImage: 'assets/images/flags/jm.png',
        nativeName: 'Jamaica',
        placeholder: '8762101234',
    },
    {
        name: 'Japan',
        code: 'JP',
        dialCode: '+81',
        flag: '🇯🇵',
        flagImage: 'assets/images/flags/jp.png',
        nativeName: '日本',
        placeholder: '09012345678',
    },
    {
        name: 'Jersey',
        code: 'JE',
        dialCode: '+44',
        flag: '🇯🇪',
        flagImage: 'assets/images/flags/je.png',
        nativeName: 'Jersey',
        placeholder: '07797712345',
    },
    {
        name: 'Jordan',
        code: 'JO',
        dialCode: '+962',
        flag: '🇯🇴',
        flagImage: 'assets/images/flags/jo.png',
        nativeName: 'الأردن',
        placeholder: '0791234567',
    },
    // K
    {
        name: 'Kazakhstan',
        code: 'KZ',
        dialCode: '+7',
        flag: '🇰🇿',
        flagImage: 'assets/images/flags/kz.png',
        nativeName: 'Қазақстан',
        placeholder: '7071234567',
    },
    {
        name: 'Kenya',
        code: 'KE',
        dialCode: '+254',
        flag: '🇰🇪',
        flagImage: 'assets/images/flags/ke.png',
        nativeName: 'Kenya',
        placeholder: '0712345678',
    },
    {
        name: 'Kiribati',
        code: 'KI',
        dialCode: '+686',
        flag: '🇰🇮',
        flagImage: 'assets/images/flags/ki.png',
        nativeName: 'Kiribati',
        placeholder: '72001234',
    },
    {
        name: 'Kosovo',
        code: 'XK',
        dialCode: '+383',
        flag: '🇽🇰',
        flagImage: '', // No flag image available for Kosovo (XK)
        nativeName: 'Kosovë',
        placeholder: '044123456',
    },
    {
        name: 'Kuwait',
        code: 'KW',
        dialCode: '+965',
        flag: '🇰🇼',
        flagImage: 'assets/images/flags/kw.png',
        nativeName: 'الكويت',
        placeholder: '51234567',
    },
    {
        name: 'Kyrgyzstan',
        code: 'KG',
        dialCode: '+996',
        flag: '🇰🇬',
        flagImage: 'assets/images/flags/kg.png',
        nativeName: 'Кыргызстан',
        placeholder: '0700123456',
    },
    // L
    {
        name: 'Laos',
        code: 'LA',
        dialCode: '+856',
        flag: '🇱🇦',
        flagImage: 'assets/images/flags/la.png',
        nativeName: 'ລາວ',
        placeholder: '020234567',
    },
    {
        name: 'Latvia',
        code: 'LV',
        dialCode: '+371',
        flag: '🇱🇻',
        flagImage: 'assets/images/flags/lv.png',
        nativeName: 'Latvija',
        placeholder: '21234567',
    },
    {
        name: 'Lebanon',
        code: 'LB',
        dialCode: '+961',
        flag: '🇱🇧',
        flagImage: 'assets/images/flags/lb.png',
        nativeName: 'لبنان',
        placeholder: '71123456',
    },
    {
        name: 'Lesotho',
        code: 'LS',
        dialCode: '+266',
        flag: '🇱🇸',
        flagImage: 'assets/images/flags/ls.png',
        nativeName: 'Lesotho',
        placeholder: '50123456',
    },
    {
        name: 'Liberia',
        code: 'LR',
        dialCode: '+231',
        flag: '🇱🇷',
        flagImage: 'assets/images/flags/lr.png',
        nativeName: 'Liberia',
        placeholder: '0770123456',
    },
    {
        name: 'Libya',
        code: 'LY',
        dialCode: '+218',
        flag: '🇱🇾',
        flagImage: 'assets/images/flags/ly.png',
        nativeName: 'ليبيا',
        placeholder: '0912345678',
    },
    {
        name: 'Liechtenstein',
        code: 'LI',
        dialCode: '+423',
        flag: '🇱🇮',
        flagImage: 'assets/images/flags/li.png',
        nativeName: 'Liechtenstein',
        placeholder: '660234567',
    },
    {
        name: 'Lithuania',
        code: 'LT',
        dialCode: '+370',
        flag: '🇱🇹',
        flagImage: 'assets/images/flags/lt.png',
        nativeName: 'Lietuva',
        placeholder: '61234567',
    },
    {
        name: 'Luxembourg',
        code: 'LU',
        dialCode: '+352',
        flag: '🇱🇺',
        flagImage: 'assets/images/flags/lu.png',
        nativeName: 'Lëtzebuerg',
        placeholder: '621123456',
    },
    // M
    {
        name: 'Macau',
        code: 'MO',
        dialCode: '+853',
        flag: '🇲🇴',
        flagImage: 'assets/images/flags/mo.png',
        nativeName: '澳門',
        placeholder: '66123456',
    },
    {
        name: 'Madagascar',
        code: 'MG',
        dialCode: '+261',
        flag: '🇲🇬',
        flagImage: 'assets/images/flags/mg.png',
        nativeName: 'Madagasikara',
        placeholder: '321234567',
    },
    {
        name: 'Malawi',
        code: 'MW',
        dialCode: '+265',
        flag: '🇲🇼',
        flagImage: 'assets/images/flags/mw.png',
        nativeName: 'Malawi',
        placeholder: '0991234567',
    },
    {
        name: 'Malaysia',
        code: 'MY',
        dialCode: '+60',
        flag: '🇲🇾',
        flagImage: 'assets/images/flags/my.png',
        nativeName: 'Malaysia',
        placeholder: '0123456789',
    },
    {
        name: 'Maldives',
        code: 'MV',
        dialCode: '+960',
        flag: '🇲🇻',
        flagImage: 'assets/images/flags/mv.png',
        nativeName: 'ދިވެހިބަސް',
        placeholder: '7771234',
    },
    {
        name: 'Mali',
        code: 'ML',
        dialCode: '+223',
        flag: '🇲🇱',
        flagImage: 'assets/images/flags/ml.png',
        nativeName: 'Mali',
        placeholder: '65012345',
    },
    {
        name: 'Malta',
        code: 'MT',
        dialCode: '+356',
        flag: '🇲🇹',
        flagImage: 'assets/images/flags/mt.png',
        nativeName: 'Malta',
        placeholder: '99123456',
    },
    {
        name: 'Marshall Islands',
        code: 'MH',
        dialCode: '+692',
        flag: '🇲🇭',
        flagImage: 'assets/images/flags/mh.png',
        nativeName: 'Marshall Islands',
        placeholder: '2351234',
    },
    {
        name: 'Martinique',
        code: 'MQ',
        dialCode: '+596',
        flag: '🇲🇶',
        flagImage: 'assets/images/flags/mq.png',
        nativeName: 'Martinique',
        placeholder: '0696201234',
    },
    {
        name: 'Mauritania',
        code: 'MR',
        dialCode: '+222',
        flag: '🇲🇷',
        flagImage: 'assets/images/flags/mr.png',
        nativeName: 'موريتانيا',
        placeholder: '22123456',
    },
    {
        name: 'Mauritius',
        code: 'MU',
        dialCode: '+230',
        flag: '🇲🇺',
        flagImage: 'assets/images/flags/mu.png',
        nativeName: 'Maurice',
        placeholder: '52512345',
    },
    {
        name: 'Mayotte',
        code: 'YT',
        dialCode: '+262',
        flag: '🇫🇷',
        flagImage: 'assets/images/flags/fr.png',
        nativeName: 'Mayotte',
        placeholder: '0639012345',
    },
    {
        name: 'Mexico',
        code: 'MX',
        dialCode: '+52',
        flag: '🇲🇽',
        flagImage: 'assets/images/flags/mx.png',
        nativeName: 'México',
        placeholder: '5512345678',
    },
    {
        name: 'Micronesia',
        code: 'FM',
        dialCode: '+691',
        flag: '🇫🇲',
        flagImage: 'assets/images/flags/fm.png',
        nativeName: 'Micronesia',
        placeholder: '3501234',
    },
    {
        name: 'Moldova',
        code: 'MD',
        dialCode: '+373',
        flag: '🇲🇩',
        flagImage: 'assets/images/flags/md.png',
        nativeName: 'Republica Moldova',
        placeholder: '0621234567',
    },
    {
        name: 'Monaco',
        code: 'MC',
        dialCode: '+377',
        flag: '🇲🇨',
        flagImage: 'assets/images/flags/mc.png',
        nativeName: 'Monaco',
        placeholder: '0612345678',
    },
    {
        name: 'Mongolia',
        code: 'MN',
        dialCode: '+976',
        flag: '🇲🇳',
        flagImage: 'assets/images/flags/mn.png',
        nativeName: 'Монгол',
        placeholder: '88123456',
    },
    {
        name: 'Montenegro',
        code: 'ME',
        dialCode: '+382',
        flag: '🇲🇪',
        flagImage: 'assets/images/flags/me.png',
        nativeName: 'Crna Gora',
        placeholder: '067123456',
    },
    {
        name: 'Montserrat',
        code: 'MS',
        dialCode: '+1664',
        flag: '🇲🇸',
        flagImage: 'assets/images/flags/ms.png',
        nativeName: 'Montserrat',
        placeholder: '6644913456',
    },
    {
        name: 'Morocco',
        code: 'MA',
        dialCode: '+212',
        flag: '🇲🇦',
        flagImage: 'assets/images/flags/ma.png',
        nativeName: 'المغرب',
        placeholder: '0612345678',
    },
    {
        name: 'Mozambique',
        code: 'MZ',
        dialCode: '+258',
        flag: '🇲🇿',
        flagImage: 'assets/images/flags/mz.png',
        nativeName: 'Moçambique',
        placeholder: '821234567',
    },
    {
        name: 'Myanmar',
        code: 'MM',
        dialCode: '+95',
        flag: '🇲🇲',
        flagImage: 'assets/images/flags/mm.png',
        nativeName: 'မြန်မာ',
        placeholder: '09212345678',
    },
    // N
    {
        name: 'Namibia',
        code: 'NA',
        dialCode: '+264',
        flag: '🇳🇦',
        flagImage: 'assets/images/flags/na.png',
        nativeName: 'Namibië',
        placeholder: '0811234567',
    },
    {
        name: 'Nauru',
        code: 'NR',
        dialCode: '+674',
        flag: '🇳🇷',
        flagImage: 'assets/images/flags/nr.png',
        nativeName: 'Nauru',
        placeholder: '5551234',
    },
    {
        name: 'Nepal',
        code: 'NP',
        dialCode: '+977',
        flag: '🇳🇵',
        flagImage: 'assets/images/flags/np.png',
        nativeName: 'नेपाल',
        placeholder: '9841234567',
    },
    {
        name: 'Netherlands',
        code: 'NL',
        dialCode: '+31',
        flag: '🇳🇱',
        flagImage: 'assets/images/flags/nl.png',
        nativeName: 'Nederland',
        placeholder: '0612345678',
    },
    {
        name: 'New Caledonia',
        code: 'NC',
        dialCode: '+687',
        flag: '🇳🇨',
        flagImage: 'assets/images/flags/nc.png',
        nativeName: 'Nouvelle-Calédonie',
        placeholder: '751234',
    },
    {
        name: 'New Zealand',
        code: 'NZ',
        dialCode: '+64',
        flag: '🇳🇿',
        flagImage: 'assets/images/flags/nz.png',
        nativeName: 'New Zealand',
        placeholder: '0212345678',
    },
    {
        name: 'Nicaragua',
        code: 'NI',
        dialCode: '+505',
        flag: '🇳🇮',
        flagImage: 'assets/images/flags/ni.png',
        nativeName: 'Nicaragua',
        placeholder: '81234567',
    },
    {
        name: 'Niger',
        code: 'NE',
        dialCode: '+227',
        flag: '🇳🇪',
        flagImage: 'assets/images/flags/ne.png',
        nativeName: 'Nijar',
        placeholder: '93123456',
    },
    {
        name: 'Nigeria',
        code: 'NG',
        dialCode: '+234',
        flag: '🇳🇬',
        flagImage: 'assets/images/flags/ng.png',
        nativeName: 'Nigeria',
        placeholder: '08012345678',
    },
    {
        name: 'Niue',
        code: 'NU',
        dialCode: '+683',
        flag: '🇳🇺',
        flagImage: 'assets/images/flags/nu.png',
        nativeName: 'Niue',
        placeholder: '1234',
    },
    {
        name: 'Norfolk Island',
        code: 'NF',
        dialCode: '+672',
        flag: '🇳🇫',
        flagImage: 'assets/images/flags/nf.png',
        nativeName: 'Norfolk Island',
        placeholder: '381234',
    },
    {
        name: 'North Korea',
        code: 'KP',
        dialCode: '+850',
        flag: '🇰🇵',
        flagImage: 'assets/images/flags/kp.png',
        nativeName: '조선 민주주의 인민 공화국',
        placeholder: '01921234567',
    },
    {
        name: 'North Macedonia',
        code: 'MK',
        dialCode: '+389',
        flag: '🇲🇰',
        flagImage: 'assets/images/flags/mk.png',
        nativeName: '+389',
        placeholder: '070234567',
    },
    {
        name: 'Northern Mariana Islands',
        code: 'MP',
        dialCode: '+1670',
        flag: '🇲🇵',
        flagImage: 'assets/images/flags/mp.png',
        nativeName: 'Northern Mariana Islands',
        placeholder: '6702352345',
    },
    {
        name: 'Norway',
        code: 'NO',
        dialCode: '+47',
        flag: '🇳🇴',
        flagImage: 'assets/images/flags/no.png',
        nativeName: 'Norge',
        placeholder: '40123456',
    },
    // O
    {
        name: 'Oman',
        code: 'OM',
        dialCode: '+968',
        flag: '🇴🇲',
        flagImage: 'assets/images/flags/om.png',
        nativeName: 'عُمان',
        placeholder: '92123456',
    },
    // P
    {
        name: 'Pakistan',
        code: 'PK',
        dialCode: '+92',
        flag: '🇵🇰',
        flagImage: 'assets/images/flags/pk.png',
        nativeName: 'پاکستان',
        placeholder: '03001234567',
    },
    {
        name: 'Palau',
        code: 'PW',
        dialCode: '+680',
        flag: '🇵🇼',
        flagImage: 'assets/images/flags/pw.png',
        nativeName: 'Palau',
        placeholder: '7701234',
    },
    {
        name: 'Palestine',
        code: 'PS',
        dialCode: '+970',
        flag: '🇵🇸',
        flagImage: 'assets/images/flags/ps.png',
        nativeName: 'فلسطين',
        placeholder: '0599123456',
    },
    {
        name: 'Panama',
        code: 'PA',
        dialCode: '+507',
        flag: '🇵🇦',
        flagImage: 'assets/images/flags/pa.png',
        nativeName: 'Panamá',
        placeholder: '61234567',
    },
    {
        name: 'Papua New Guinea',
        code: 'PG',
        dialCode: '+675',
        flag: '🇵🇬',
        flagImage: 'assets/images/flags/pg.png',
        nativeName: 'Papua New Guinea',
        placeholder: '70123456',
    },
    {
        name: 'Paraguay',
        code: 'PY',
        dialCode: '+595',
        flag: '🇵🇾',
        flagImage: 'assets/images/flags/py.png',
        nativeName: 'Paraguay',
        placeholder: '0961234567',
    },
    {
        name: 'Peru',
        code: 'PE',
        dialCode: '+51',
        flag: '🇵🇪',
        flagImage: 'assets/images/flags/pe.png',
        nativeName: 'Perú',
        placeholder: '987654321',
    },
    {
        name: 'Philippines',
        code: 'PH',
        dialCode: '+63',
        flag: '🇵🇭',
        flagImage: 'assets/images/flags/ph.png',
        nativeName: 'Philippines',
        placeholder: '09171234567',
    },
    {
        name: 'Pitcairn',
        code: 'PN',
        dialCode: '+64',
        flag: '🇵🇳',
        flagImage: 'assets/images/flags/pn.png',
        nativeName: 'Pitcairn Islands',
    },
    {
        name: 'Poland',
        code: 'PL',
        dialCode: '+48',
        flag: '🇵🇱',
        flagImage: 'assets/images/flags/pl.png',
        nativeName: 'Polska',
        placeholder: '501234567',
    },
    {
        name: 'Portugal',
        code: 'PT',
        dialCode: '+351',
        flag: '🇵🇹',
        flagImage: 'assets/images/flags/pt.png',
        nativeName: 'Portugal',
        placeholder: '912345678',
    },
    {
        name: 'Puerto Rico',
        code: 'PR',
        dialCode: '+1',
        flag: '🇵🇷',
        flagImage: 'assets/images/flags/pr.png',
        nativeName: 'Puerto Rico',
        placeholder: '7872345678',
    },
    // Q
    {
        name: 'Qatar',
        code: 'QA',
        dialCode: '+974',
        flag: '🇶🇦',
        flagImage: 'assets/images/flags/qa.png',
        nativeName: 'قطر',
        placeholder: '33123456',
    },
    // R
    {
        name: 'Réunion',
        code: 'RE',
        dialCode: '+262',
        flag: '🇫🇷',
        flagImage: 'assets/images/flags/mf.png',
        nativeName: 'La Réunion',
        placeholder: '0692123456',
    },
    {
        name: 'Romania',
        code: 'RO',
        dialCode: '+40',
        flag: '🇷🇴',
        flagImage: 'assets/images/flags/ro.png',
        nativeName: 'România',
        placeholder: '0712345678',
    },
    {
        name: 'Russia',
        code: 'RU',
        dialCode: '+7',
        flag: '🇷🇺',
        flagImage: 'assets/images/flags/ru.png',
        nativeName: 'Россия',
        placeholder: '9123456789',
    },
    {
        name: 'Rwanda',
        code: 'RW',
        dialCode: '+250',
        flag: '🇷🇼',
        flagImage: 'assets/images/flags/rw.png',
        nativeName: 'Rwanda',
        placeholder: '0781234567',
    },
    // S
    {
        name: 'Saint Barthélemy',
        code: 'BL',
        dialCode: '+590',
        flag: '🇫🇷',
        flagImage: 'assets/images/flags/fr.png',
        nativeName: 'Saint-Barthélemy',
        placeholder: '0690001234',
    },
    {
        name: 'Saint Helena',
        code: 'SH',
        dialCode: '+290',
        flag: '🇸🇭',
        flagImage: 'assets/images/flags/sh.png',
        nativeName: 'Saint Helena',
        placeholder: '62158',
    },
    {
        name: 'Saint Kitts and Nevis',
        code: 'KN',
        dialCode: '+1869',
        flag: '🇰🇳',
        flagImage: 'assets/images/flags/kn.png',
        nativeName: 'Saint Kitts and Nevis',
        placeholder: '8694651234',
    },
    {
        name: 'Saint Lucia',
        code: 'LC',
        dialCode: '+1758',
        flag: '🇱🇨',
        flagImage: 'assets/images/flags/lc.png',
        nativeName: 'Saint Lucia',
        placeholder: '7582841234',
    },
    {
        name: 'Saint Martin (France)',
        code: 'MF',
        dialCode: '+590',
        flag: '🇲🇫',
        flagImage: 'assets/images/flags/mf.png',
        nativeName: 'Saint-Martin',
        placeholder: '0690001234',
    },
    {
        name: 'Saint Pierre and Miquelon',
        code: 'PM',
        dialCode: '+508',
        flag: '🇫🇷',
        flagImage: 'assets/images/flags/fr.png',
        nativeName: 'Saint-Pierre-et-Miquelon',
        placeholder: '0508123456',
    },
    {
        name: 'Saint Vincent and the Grenadines',
        code: 'VC',
        dialCode: '+1784',
        flag: '🇻🇨',
        flagImage: 'assets/images/flags/vc.png',
        nativeName: 'Saint Vincent and the Grenadines',
        placeholder: '7844301234',
    },
    {
        name: 'Samoa',
        code: 'WS',
        dialCode: '+685',
        flag: '🇼🇸',
        flagImage: 'assets/images/flags/ws.png',
        nativeName: 'Samoa',
        placeholder: '7212345',
    },
    {
        name: 'San Marino',
        code: 'SM',
        dialCode: '+378',
        flag: '🇸🇲',
        flagImage: 'assets/images/flags/sm.png',
        nativeName: 'San Marino',
        placeholder: '66661234',
    },
    {
        name: 'São Tomé and Príncipe',
        code: 'ST',
        dialCode: '+239',
        flag: '🇸🇹',
        flagImage: 'assets/images/flags/st.png',
        nativeName: 'São Tomé e Príncipe',
        placeholder: '9812345',
    },
    {
        name: 'Saudi Arabia',
        code: 'SA',
        dialCode: '+966',
        flag: '🇸🇦',
        flagImage: 'assets/images/flags/sa.png',
        nativeName: 'المملكة العربية السعودية',
        placeholder: '501234567',
    },
    {
        name: 'Senegal',
        code: 'SN',
        dialCode: '+221',
        flag: '🇸🇳',
        flagImage: 'assets/images/flags/sn.png',
        nativeName: 'Sénégal',
        placeholder: '701234567',
    },
    {
        name: 'Serbia',
        code: 'RS',
        dialCode: '+381',
        flag: '🇷🇸',
        flagImage: 'assets/images/flags/rs.png',
        nativeName: 'Србија',
        placeholder: '0601234567',
    },
    {
        name: 'Seychelles',
        code: 'SC',
        dialCode: '+248',
        flag: '🇸🇨',
        flagImage: 'assets/images/flags/sc.png',
        nativeName: 'Seychelles',
        placeholder: '2512345',
    },
    {
        name: 'Sierra Leone',
        code: 'SL',
        dialCode: '+232',
        flag: '🇸🇱',
        flagImage: 'assets/images/flags/sl.png',
        nativeName: 'Sierra Leone',
        placeholder: '076123456',
    },
    {
        name: 'Singapore',
        code: 'SG',
        dialCode: '+65',
        flag: '🇸🇬',
        flagImage: 'assets/images/flags/sg.png',
        nativeName: 'Singapore',
        placeholder: '81234567',
    },
    {
        name: 'Sint Maarten',
        code: 'SX',
        dialCode: '+1721',
        flag: '🇸🇽',
        flagImage: 'assets/images/flags/sx.png',
        nativeName: 'Sint Maarten',
        placeholder: '7215201234',
    },
    {
        name: 'Slovakia',
        code: 'SK',
        dialCode: '+421',
        flag: '🇸🇰',
        flagImage: 'assets/images/flags/sk.png',
        nativeName: 'Slovensko',
        placeholder: '0912123456',
    },
    {
        name: 'Slovenia',
        code: 'SI',
        dialCode: '+386',
        flag: '🇸🇮',
        flagImage: 'assets/images/flags/si.png',
        nativeName: 'Slovenija',
        placeholder: '031234567',
    },
    {
        name: 'Solomon Islands',
        code: 'SB',
        dialCode: '+677',
        flag: '🇸🇧',
        flagImage: 'assets/images/flags/sb.png',
        nativeName: 'Solomon Islands',
        placeholder: '7412345',
    },
    {
        name: 'Somalia',
        code: 'SO',
        dialCode: '+252',
        flag: '🇸🇴',
        flagImage: 'assets/images/flags/so.png',
        nativeName: 'Soomaaliya',
        placeholder: '0612345678',
    },
    {
        name: 'South Africa',
        code: 'ZA',
        dialCode: '+27',
        flag: '🇿🇦',
        flagImage: 'assets/images/flags/za.png',
        nativeName: 'South Africa',
        placeholder: '0712345678',
    },
    {
        name: 'South Korea',
        code: 'KR',
        dialCode: '+82',
        flag: '🇰🇷',
        flagImage: 'assets/images/flags/kr.png',
        nativeName: '대한민국',
        placeholder: '01012345678',
    },
    {
        name: 'South Sudan',
        code: 'SS',
        dialCode: '+211',
        flag: '🇸🇸',
        flagImage: 'assets/images/flags/ss.png',
        nativeName: 'جنوب السودان',
        placeholder: '0977123456',
    },
    {
        name: 'Spain',
        code: 'ES',
        dialCode: '+34',
        flag: '🇪🇸',
        flagImage: 'assets/images/flags/es.png',
        nativeName: 'España',
        placeholder: '612345678',
    },
    {
        name: 'Sri Lanka',
        code: 'LK',
        dialCode: '+94',
        flag: '🇱🇰',
        flagImage: 'assets/images/flags/lk.png',
        nativeName: 'ශ්‍රී ලංකාව',
        placeholder: '0712345678',
    },
    {
        name: 'Sudan',
        code: 'SD',
        dialCode: '+249',
        flag: '🇸🇩',
        flagImage: 'assets/images/flags/sd.png',
        nativeName: 'السودان',
        placeholder: '0912345678',
    },
    {
        name: 'Suriname',
        code: 'SR',
        dialCode: '+597',
        flag: '🇸🇷',
        flagImage: 'assets/images/flags/sr.png',
        nativeName: 'Suriname',
        placeholder: '7412345',
    },
    {
        name: 'Svalbard and Jan Mayen',
        code: 'SJ',
        dialCode: '+47',
        flag: '🇸🇯',
        flagImage: 'assets/images/flags/sj.png',
        nativeName: 'Svalbard og Jan Mayen',
        placeholder: '79912345',
    },
    {
        name: 'Sweden',
        code: 'SE',
        dialCode: '+46',
        flag: '🇸🇪',
        flagImage: 'assets/images/flags/se.png',
        nativeName: 'Sverige',
        placeholder: '0701234567',
    },
    {
        name: 'Switzerland',
        code: 'CH',
        dialCode: '+41',
        flag: '🇨🇭',
        flagImage: 'assets/images/flags/ch.png',
        nativeName: 'Schweiz',
        placeholder: '0791234567',
    },
    {
        name: 'Syria',
        code: 'SY',
        dialCode: '+963',
        flag: '🇸🇾',
        flagImage: 'assets/images/flags/sy.png',
        nativeName: 'سوريا',
        placeholder: '0944567890',
    },
    // T
    {
        name: 'Taiwan',
        code: 'TW',
        dialCode: '+886',
        flag: '🇹🇼',
        flagImage: 'assets/images/flags/tw.png',
        nativeName: '台灣',
        placeholder: '0912345678',
    },
    {
        name: 'Tajikistan',
        code: 'TJ',
        dialCode: '+992',
        flag: '🇹🇯',
        flagImage: 'assets/images/flags/tj.png',
        nativeName: 'Tajikistan',
        placeholder: '917123456',
    },
    {
        name: 'Tanzania',
        code: 'TZ',
        dialCode: '+255',
        flag: '🇹🇿',
        flagImage: 'assets/images/flags/tz.png',
        nativeName: 'Tanzania',
        placeholder: '0712345678',
    },
    {
        name: 'Thailand',
        code: 'TH',
        dialCode: '+66',
        flag: '🇹🇭',
        flagImage: 'assets/images/flags/th.png',
        nativeName: 'ไทย',
        placeholder: '0812345678',
    },
    {
        name: 'Timor-Leste',
        code: 'TL',
        dialCode: '+670',
        flag: '🇹🇱',
        flagImage: 'assets/images/flags/tl.png',
        nativeName: 'Timor-Leste',
        placeholder: '77212345',
    },
    {
        name: 'Togo',
        code: 'TG',
        dialCode: '+228',
        flag: '🇹🇬',
        flagImage: 'assets/images/flags/tg.png',
        nativeName: 'Togo',
        placeholder: '90112345',
    },
    {
        name: 'Tokelau',
        code: 'TK',
        dialCode: '+690',
        flag: '🇹🇰',
        flagImage: 'assets/images/flags/tk.png',
        nativeName: 'Tokelau',
    },
    {
        name: 'Tonga',
        code: 'TO',
        dialCode: '+676',
        flag: '🇹🇴',
        flagImage: 'assets/images/flags/to.png',
        nativeName: 'Tonga',
        placeholder: '7715123',
    },
    {
        name: 'Trinidad and Tobago',
        code: 'TT',
        dialCode: '+1868',
        flag: '🇹🇹',
        flagImage: 'assets/images/flags/tt.png',
        nativeName: 'Trinidad and Tobago',
        placeholder: '8682911234',
    },
    {
        name: 'Tunisia',
        code: 'TN',
        dialCode: '+216',
        flag: '🇹🇳',
        flagImage: 'assets/images/flags/tn.png',
        nativeName: 'تونس',
        placeholder: '20123456',
    },
    {
        name: 'Turkey',
        code: 'TR',
        dialCode: '+90',
        flag: '🇹🇷',
        flagImage: 'assets/images/flags/tr.png',
        nativeName: 'Türkiye',
        placeholder: '5321234567',
    },
    {
        name: 'Turkmenistan',
        code: 'TM',
        dialCode: '+993',
        flag: '🇹🇲',
        flagImage: 'assets/images/flags/tm.png',
        nativeName: 'Turkmenistan',
        placeholder: '65123456',
    },
    {
        name: 'Turks and Caicos Islands',
        code: 'TC',
        dialCode: '+1649',
        flag: '🇹🇨',
        flagImage: 'assets/images/flags/tc.png',
        nativeName: 'Turks and Caicos Islands',
        placeholder: '6493311234',
    },
    {
        name: 'Tuvalu',
        code: 'TV',
        dialCode: '+688',
        flag: '🇹🇻',
        flagImage: 'assets/images/flags/tv.png',
        nativeName: 'Tuvalu',
        placeholder: '901234',
    },
    // U
    {
        name: 'Uganda',
        code: 'UG',
        dialCode: '+256',
        flag: '🇺🇬',
        flagImage: 'assets/images/flags/ug.png',
        nativeName: 'Uganda',
        placeholder: '0712345678',
    },
    {
        name: 'Ukraine',
        code: 'UA',
        dialCode: '+380',
        flag: '🇺🇦',
        flagImage: 'assets/images/flags/ua.png',
        nativeName: 'Україна',
        placeholder: '0671234567',
    },
    {
        name: 'United Arab Emirates',
        code: 'AE',
        dialCode: '+971',
        flag: '🇦🇪',
        flagImage: 'assets/images/flags/ae.png',
        nativeName: 'الإمارات العربية المتحدة',
        placeholder: '0501234567',
    },
    // { // Move this in top
    //     name: 'United Kingdom'
    //     code: 'GB'
    //     dialCode: '+44'
    //     flag: '🇬🇧'
    //     flagImage: 'assets/images/flags/gb.png'
    //     nativeName: '+44',
    //
    //
    //
    //
    // },
    // { // Move this in top
    //     name: 'United States'
    //     code: 'US'
    //     dialCode: '+1'
    //     flag: '🇺🇸'
    //     flagImage: 'assets/images/flags/us.png'
    //     nativeName: '+1',
    //
    //
    //
    //
    // },
    {
        name: 'Uruguay',
        code: 'UY',
        dialCode: '+598',
        flag: '🇺🇾',
        flagImage: 'assets/images/flags/uy.png',
        nativeName: 'Uruguay',
        placeholder: '094231234',
    },
    {
        name: 'US Virgin Islands',
        code: 'VI',
        dialCode: '+1340',
        flag: '🇻🇮',
        flagImage: 'assets/images/flags/vi.png',
        nativeName: 'U.S. Virgin Islands',
        placeholder: '3403411234',
    },
    {
        name: 'Uzbekistan',
        code: 'UZ',
        dialCode: '+998',
        flag: '🇺🇿',
        flagImage: 'assets/images/flags/uz.png',
        nativeName: 'Oʻzbekiston',
        placeholder: '901234567',
    },
    // V
    {
        name: 'Vanuatu',
        code: 'VU',
        dialCode: '+678',
        flag: '🇻🇺',
        flagImage: 'assets/images/flags/vu.png',
        nativeName: 'Vanuatu',
        placeholder: '5912345',
    },
    {
        name: 'Vatican City',
        code: 'VA',
        dialCode: '+379', // Old +39
        flag: '🇻🇦',
        flagImage: 'assets/images/flags/va.png',
        nativeName: 'Città del Vaticano',
        placeholder: '3451234',
    },
    {
        name: 'Venezuela',
        code: 'VE',
        dialCode: '+58',
        flag: '🇻🇪',
        flagImage: 'assets/images/flags/ve.png',
        nativeName: 'Venezuela',
        placeholder: '4121234567',
    },
    {
        name: 'Vietnam',
        code: 'VN',
        dialCode: '+84',
        flag: '🇻🇳',
        flagImage: 'assets/images/flags/vn.png',
        nativeName: 'Việt Nam',
        placeholder: '0912345678',
    },
    // W
    {
        name: 'Wallis and Futuna',
        code: 'WF',
        dialCode: '+681',
        flag: '🇫🇷',
        flagImage: 'assets/images/flags/fr.png',
        nativeName: 'Wallis-et-Futuna',
        placeholder: '501234',
    },
    {
        name: 'Western Sahara',
        code: 'EH',
        dialCode: '+212',
        flag: '🇪🇭',
        flagImage: 'assets/images/flags/eh.png',
        nativeName: 'الصحراء الغربية',
        placeholder: '0612345678',
    },
    // Y
    {
        name: 'Yemen',
        code: 'YE',
        dialCode: '+967',
        flag: '🇾🇪',
        flagImage: 'assets/images/flags/ye.png',
        nativeName: 'اليمن',
        placeholder: '0712345678',
    },
    // Z
    {
        name: 'Zambia',
        code: 'ZM',
        dialCode: '+260',
        flag: '🇿🇲',
        flagImage: 'assets/images/flags/zm.png',
        nativeName: 'Zambia',
        placeholder: '0971234567',
    },
    {
        name: 'Zimbabwe',
        code: 'ZW',
        dialCode: '+263',
        flag: '🇿🇼',
        flagImage: 'assets/images/flags/zw.png',
        nativeName: 'Zimbabwe',
        placeholder: '0712345678',
    },
];
