name: Build check

on:
  pull_request:
    branches:
      - development
      - main
      - production
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository using the latest version
      - name: Check out Git repository
        uses: actions/checkout@v4  # Update to v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Fetch branches
        run: git fetch --no-tags --prune --depth=5

      # Install Node.js & NPM using the latest setup-node action
      - name: Install Node.js & NPM
        uses: actions/setup-node@v3  # Ensure v3 is used here
        with:
          node-version: "20"  # Ensure Node.js 20 is used

      # Runs npm install
      - uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0
        with:
          useRollingCache: true
          working-directory: .
          install-command: npm ci --audit false

      - name: Starting build check
        shell: bash
        run: echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
        id: extract_branch

      # Conditional build steps based on the target branch
      - if: ${{github.event.pull_request.base.ref == 'main'}}
        run: npx nx affected --target=build --base='origin/main' --configuration=local

      - if: ${{github.event.pull_request.base.ref == 'production'}}
        run: npx nx affected --target=build --base='origin/production' --configuration=local

      - if: ${{github.event.pull_request.base.ref == 'development'}}
        run: npx nx affected --target=build --base='origin/development' --configuration=local
